// ─── UI Strings (all 5 languages) ───────────────────────────────────────────

export const LANGUAGES = ['en', 'es', 'de', 'pt', 'fr'];

export const uiStrings = {
  en: {
    // Header
    home: 'home',
    docs: 'docs',
    github: 'github',
    docsTag: 'docs',

    // Search
    searchPlaceholder: 'Search...',
    searchKbd: '⌘K',
    noResults: 'No results found',

    // Sidebar
    toggleSidebar: 'Toggle sidebar',

    // Breadcrumbs
    breadcrumbDocs: 'Docs',

    // Page nav
    previous: 'Previous',
    next: 'Next',

    // Footer
    footerText: 'MIT License',
    footerBuiltWith: 'Built with Rust & Tokio',

    // 404
    notFoundTitle: 'Not Found',
    notFoundHeading: '404',
    notFoundMessage: 'Page not found.',
    notFoundLink: 'Return to documentation',

    // Section names (used in sidebar and breadcrumbs)
    sections: {
      'Getting Started': 'Getting Started',
      'Configuration': 'Configuration',
      'Telegram': 'Telegram',
      'Slack': 'Slack',
      'Discord': 'Discord',
      'Tools': 'Tools',
      'MCP': 'MCP',
      'Triggers': 'Triggers',
      'Skills': 'Skills',
      'Scheduler': 'Scheduler',
      'Router': 'Router',
      'Cost Tracking': 'Cost Tracking',
      'Architecture': 'Architecture',
      'Service': 'Service',
      'Event Sourcing': 'Event Sourcing',
      'Plans': 'Plans',
      'Health Monitoring': 'Health Monitoring',
      'Updates': 'Updates',
    },
  },

  es: {
    home: 'inicio',
    docs: 'docs',
    github: 'github',
    docsTag: 'docs',
    searchPlaceholder: 'Buscar...',
    searchKbd: '⌘K',
    noResults: 'No se encontraron resultados',
    toggleSidebar: 'Alternar barra lateral',
    breadcrumbDocs: 'Docs',
    previous: 'Anterior',
    next: 'Siguiente',
    footerText: 'Licencia MIT',
    footerBuiltWith: 'Construido con Rust y Tokio',
    notFoundTitle: 'No encontrado',
    notFoundHeading: '404',
    notFoundMessage: 'Página no encontrada.',
    notFoundLink: 'Volver a la documentación',
    sections: {
      'Getting Started': 'Primeros Pasos',
      'Configuration': 'Configuración',
      'Telegram': 'Telegram',
      'Slack': 'Slack',
      'Discord': 'Discord',
      'Tools': 'Herramientas',
      'MCP': 'MCP',
      'Triggers': 'Disparadores',
      'Skills': 'Habilidades',
      'Scheduler': 'Programador',
      'Router': 'Enrutador',
      'Cost Tracking': 'Seguimiento de Costos',
      'Architecture': 'Arquitectura',
      'Service': 'Servicio',
      'Event Sourcing': 'Registro de Eventos',
      'Plans': 'Planes',
      'Health Monitoring': 'Monitoreo de Salud',
      'Updates': 'Actualizaciones',
    },
  },

  de: {
    home: 'startseite',
    docs: 'docs',
    github: 'github',
    docsTag: 'docs',
    searchPlaceholder: 'Suchen...',
    searchKbd: '⌘K',
    noResults: 'Keine Ergebnisse gefunden',
    toggleSidebar: 'Seitenleiste umschalten',
    breadcrumbDocs: 'Docs',
    previous: 'Zurück',
    next: 'Weiter',
    footerText: 'MIT-Lizenz',
    footerBuiltWith: 'Erstellt mit Rust & Tokio',
    notFoundTitle: 'Nicht gefunden',
    notFoundHeading: '404',
    notFoundMessage: 'Seite nicht gefunden.',
    notFoundLink: 'Zurück zur Dokumentation',
    sections: {
      'Getting Started': 'Erste Schritte',
      'Configuration': 'Konfiguration',
      'Telegram': 'Telegram',
      'Slack': 'Slack',
      'Discord': 'Discord',
      'Tools': 'Werkzeuge',
      'MCP': 'MCP',
      'Triggers': 'Auslöser',
      'Skills': 'Fähigkeiten',
      'Scheduler': 'Planer',
      'Router': 'Router',
      'Cost Tracking': 'Kostenverfolgung',
      'Architecture': 'Architektur',
      'Service': 'Dienst',
      'Event Sourcing': 'Ereignisprotokoll',
      'Plans': 'Pläne',
      'Health Monitoring': 'Gesundheitsüberwachung',
      'Updates': 'Aktualisierungen',
    },
  },

  pt: {
    home: 'início',
    docs: 'docs',
    github: 'github',
    docsTag: 'docs',
    searchPlaceholder: 'Pesquisar...',
    searchKbd: '⌘K',
    noResults: 'Nenhum resultado encontrado',
    toggleSidebar: 'Alternar barra lateral',
    breadcrumbDocs: 'Docs',
    previous: 'Anterior',
    next: 'Próximo',
    footerText: 'Licença MIT',
    footerBuiltWith: 'Construído com Rust e Tokio',
    notFoundTitle: 'Não encontrado',
    notFoundHeading: '404',
    notFoundMessage: 'Página não encontrada.',
    notFoundLink: 'Voltar à documentação',
    sections: {
      'Getting Started': 'Primeiros Passos',
      'Configuration': 'Configuração',
      'Telegram': 'Telegram',
      'Slack': 'Slack',
      'Discord': 'Discord',
      'Tools': 'Ferramentas',
      'MCP': 'MCP',
      'Triggers': 'Gatilhos',
      'Skills': 'Habilidades',
      'Scheduler': 'Agendador',
      'Router': 'Roteador',
      'Cost Tracking': 'Rastreamento de Custos',
      'Architecture': 'Arquitetura',
      'Service': 'Serviço',
      'Event Sourcing': 'Registro de Eventos',
      'Plans': 'Planos',
      'Health Monitoring': 'Monitoramento de Saúde',
      'Updates': 'Atualizações',
    },
  },

  fr: {
    home: 'accueil',
    docs: 'docs',
    github: 'github',
    docsTag: 'docs',
    searchPlaceholder: 'Rechercher...',
    searchKbd: '⌘K',
    noResults: 'Aucun résultat trouvé',
    toggleSidebar: 'Basculer la barre latérale',
    breadcrumbDocs: 'Docs',
    previous: 'Précédent',
    next: 'Suivant',
    footerText: 'Licence MIT',
    footerBuiltWith: 'Construit avec Rust et Tokio',
    notFoundTitle: 'Non trouvé',
    notFoundHeading: '404',
    notFoundMessage: 'Page non trouvée.',
    notFoundLink: 'Retour à la documentation',
    sections: {
      'Getting Started': 'Premiers Pas',
      'Configuration': 'Configuration',
      'Telegram': 'Telegram',
      'Slack': 'Slack',
      'Discord': 'Discord',
      'Tools': 'Outils',
      'MCP': 'MCP',
      'Triggers': 'Déclencheurs',
      'Skills': 'Compétences',
      'Scheduler': 'Planificateur',
      'Router': 'Routeur',
      'Cost Tracking': 'Suivi des Coûts',
      'Architecture': 'Architecture',
      'Service': 'Service',
      'Event Sourcing': 'Journal des Événements',
      'Plans': 'Plans',
      'Health Monitoring': 'Surveillance de Santé',
      'Updates': 'Mises à Jour',
    },
  },
};
